# Generated by Django 5.2.4 on 2025-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='answer_formatted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='explanation_formatted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='has_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिंदी)'), ('te', 'Telugu (తెలుగు)'), ('ur', 'Urdu (اردو)'), ('ar', 'Arabic (العربية)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('zh', 'Chinese (中文)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('ru', 'Russian (Русский)'), ('pt', 'Portuguese (Português)'), ('it', 'Italian (Italiano)'), ('bn', 'Bengali (বাংলা)'), ('ta', 'Tamil (தமிழ்)'), ('ml', 'Malayalam (മലയാളം)'), ('kn', 'Kannada (ಕನ್ನಡ)'), ('gu', 'Gujarati (ગુજરાતી)'), ('mr', 'Marathi (मराठी)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='math_expressions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='mathematical_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic (Arithmetic)'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('trigonometry', 'Trigonometry'), ('calculus', 'Calculus'), ('statistics', 'Statistics'), ('discrete', 'Discrete Math'), ('advanced', 'Advanced Mathematics')], max_length=20),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='options_formatted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='question_text_formatted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('mathematical', 'Mathematical'), ('scientific', 'Scientific'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='mathematical_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic (Arithmetic)'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('trigonometry', 'Trigonometry'), ('calculus', 'Calculus'), ('statistics', 'Statistics'), ('discrete', 'Discrete Math'), ('advanced', 'Advanced Mathematics')], max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='reading_direction',
            field=models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], default='ltr', max_length=3),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='script_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='detected_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिंदी)'), ('te', 'Telugu (తెలుగు)'), ('ur', 'Urdu (اردو)'), ('ar', 'Arabic (العربية)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('zh', 'Chinese (中文)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('ru', 'Russian (Русский)'), ('pt', 'Portuguese (Português)'), ('it', 'Italian (Italiano)'), ('bn', 'Bengali (বাংলা)'), ('ta', 'Tamil (தமிழ்)'), ('ml', 'Malayalam (മലയാളം)'), ('kn', 'Kannada (ಕನ್ನಡ)'), ('gu', 'Gujarati (ગુજરાતી)'), ('mr', 'Marathi (मराठी)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
