# Generated by Django 5.2.4 on 2025-07-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_uploadedfile_options_remove_taskresult_user_and_more'),
    ]

    operations = [
    ]
