# Generated by Django 5.2.4 on 2025-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_safe_multilingual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='detected_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='mathematical_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='reading_direction',
            field=models.CharField(default='ltr', max_length=3),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='script_type',
            field=models.CharField(blank=True, default='latin', max_length=50),
        ),
    ]
